OZO: Related functions
Related functions
Database connection
Description
Connection related functions.
Functions
template<typename T >
decltype(auto) constexpr ozo::unwrap_connection (T &&conn) noexcept
Unwrap connection if wrapped with Nullable.
template<typename T >
constexpr auto ozo::get_connection_oid_map (T &&conn)
Get the connection oid map object.
template<typename T >
constexpr auto ozo::get_connection_socket (T &&conn)
Get the connection socket object.
template<typename T >
constexpr auto ozo::get_connection_handle (T &&conn)
Get the connection handle object.
template<typename T >
constexpr auto ozo::get_connection_error_context (T &&conn)
Get the connection error context object.
template<typename T >
constexpr auto ozo::get_connection_timer (T &&conn)
Get the connection timer object.
template<typename T >
decltype(auto) ozo::get_handle (T &&conn) noexcept
PostgreSQL connection handle.
template<typename T >
decltype(auto) ozo::get_native_handle (T &&conn) noexcept
PostgreSQL native connection handle.
template<typename T >
decltype(auto) ozo::get_socket (T &&conn) noexcept
Socket stream object of the connection.
template<typename T >
decltype(auto) ozo::get_io_context (T &conn) noexcept
IO context for a connection is bound to.
template<typename T , typename IoContext >
error_code ozo::rebind_io_context (T &conn, IoContext &io)
Rebinds io_context for the connection.
template<typename T >
bool ozo::connection_bad (const T &conn) noexcept
Indicates if connection state is bad.
template<typename T >
bool ozo::connection_good (const T &conn) noexcept
Indicates if connection state is not bad.
template<typename T >
std::string_view ozo::error_message (T &&conn)
Gives native libpq error message.
template<typename T >
const auto & ozo::get_error_context (const T &conn)
Gives additional error context from OZO.
template<typename T , typename Ctx >
void ozo::set_error_context (T &conn, Ctx &&ctx)
Set connection OZO-related error context.
template<typename T >
void ozo::reset_error_context (T &conn)
Reset connection OZO-related error context.
template<typename T >
decltype(auto) ozo::get_oid_map (T &&conn) noexcept
Access to a connection OID map.
template<typename T >
decltype(auto) ozo::get_statistics (T &&conn) noexcept
Access to a Connection statistics.
template<typename T >
decltype(auto) ozo::get_timer (T &&conn) noexcept
Access to a timer for connection operations.
template<typename T , typename CompletionToken >
auto ozo::get_connection (T &&provider, CompletionToken &&token)
Get a connection from provider.
template<typename T >
void ozo::close_connection (T &&conn)
Close connection to the database immediately.
template<typename Source >
auto make_connection_pool (Source &&source, const connection_pool_config &config)
Connection pool construct helper function.
Function Documentation
close_connection()
template<typename T > void ozo::close_connection (T && conn)
Close connection to the database immediately.
This function closes connection to the database immediately.
Note
No query cancel operation will be made while closing connection. Use the function with attention - non cancelled query can still produce a work on server-side and consume resources. So it is better to use ozo::cancel() function.
Parameters
conn — Connection to be closed
References ozo::get_handle(), and ozo::get_socket().
connection_bad()
template<typename T > bool ozo::connection_bad (const T & conn) noexcept
Indicates if connection state is bad.
If conn is Nullable - checks for null state first via operator !().
Parameters
conn — Connection object to check
Returns
true if connection is in bad or null state, false - otherwise.
References ozo::get_native_handle().
Referenced by ozo::connection_good().
connection_good()
template<typename T > bool ozo::connection_good (const T & conn) noexcept
Indicates if connection state is not bad.
See ozo::connection_bad for details.
Parameters
conn — Connection to check
Returns
false if connection is in bad state, true - otherwise
References ozo::connection_bad().
error_message()
template<typename T > std::string_view ozo::error_message (T && conn)
Gives native libpq error message.
Underlying libpq provides additional textual context for different errors which can be while interacting via connection. This function gives access for such messages.
Parameters
conn — Connection to get message from
Returns
std::string_view contains a message
References ozo::get_native_handle().
get_connection()
template<typename T , typename CompletionToken > auto ozo::get_connection (T && provider, CompletionToken && token)
Get a connection from provider.
Function allows to get Connection from ConnectionProvider in asynchronous way. There is built-in customization for Connection which provides connection itself and resets it's error context.
Customization point
This is a customization point of ConnectionProvider. By default ConnectionProvider must have async_get_connection() member function with signature:
void async_get_connection(Handler&& h);
where Handler must be a functor with such or compatible signature:
void (error_code ec, connection_type<ConnectionProvider> conn);
This behaviour can be customized via async_get_connection_impl specialization. E.g. for Connection possible customization may looks like this (exposition only):
template <typename T>
struct async_get_connection_impl<T, Require<Connection<T>>> {
    template <typename Conn, typename Handler>
    static constexpr void apply(Conn&& c, Handler&& h) {
        reset_error_context(c);
        decltype(auto) io = get_io_context(c);
        asio::dispatch(io, detail::bind(
            std::forward<Handler>(h), error_code{}, std::forward<Conn>(c)));
    }
};
Parameters
provider — ConnectionProvider to get connection from
token — completion token which determines the continuation of operation; it can be a callback, a boost::asio::yield_context, a boost::use_future and other Boost.Asio compatible tokens.
Returns
completion token depent value like void for callback, connection for the yield_context, std::future<connection> for use_future, and so on.
get_connection_error_context()
template<typename T > constexpr auto ozo::get_connection_error_context (T && conn)
Get the connection error context object.
Connection OZO error context getter. In many cases the error_code is a good thing, but sometimes you need an additional context which unlucky can not be placed inside an error_code object. To solve this problem this additional error context is introduced. Usually it returns a reference to an std::string object. The error context is reset inside get_connection implementation for Connection.
Customization Point
This is customization point for Connection concept implementation. To customize it please specialize ozo::get_connection_error_context_impl template. Default specialization may look like this (for exposition only):
template <typename T, typename = std::void_t<>>
struct get_connection_error_context_impl {
    template <typename Conn>
    constexpr static auto apply(Conn&& c) -> decltype((c.error_context_)) {
        return c.error_context_;
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — Connection object
Returns
additional error context, for now std::string is supported only
Referenced by ozo::get_error_context(), and ozo::set_error_context().
get_connection_handle()
template<typename T > constexpr auto ozo::get_connection_handle (T && conn)
Get the connection handle object.
PosgreSQL connection handle getter. In general it must return reference or proxy object to ozo::native_conn_handle object.
Customization Point
This is customization point for Connection concept implementation. To customize it please specialize ozo::get_connection_handle_impl template. Default specialization may look like this (for exposition only):
template <typename T, typename = std::void_t<>>
struct get_connection_handle_impl {
    template <typename Conn>
    constexpr static auto apply(Conn&& c) -> decltype((c.handle_)) {
        return c.handle_;
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — Connection object
Returns
reference or proxy object to ozo::native_conn_handle object
Referenced by ozo::get_handle().
get_connection_oid_map()
template<typename T > constexpr auto ozo::get_connection_oid_map (T && conn)
Get the connection oid map object.
Connection types' OID map getter. This function must be specified for a Connection concept implementation to be conform to. Function must return reference to ozo::oid_map_t template specialization or proxy class object to access connection's types' OID map.
Customization Point
This is customization point for Connection concept implementation. To customize it please specialize ozo::get_connection_oid_map_impl template. Default specialization may look like this (for exposition only):
template <typename T, typename = std::void_t<>>
struct get_connection_oid_map_impl {
    template <typename Conn>
    constexpr static auto apply(Conn&& c) -> decltype((c.oid_map_)) {
        return c.oid_map_;
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — Connection object
Returns
reference or proxy to OID map object.
Referenced by ozo::get_oid_map().
get_connection_socket()
template<typename T > constexpr auto ozo::get_connection_socket (T && conn)
Get the connection socket object.
Connection socket object getter. Connection must provide socket for IO. In general it must return reference to an instance of boost::asio::posix::stream_descriptor.
Customization Point
This is customization point for Connection concept implementation. To customize it please specialize ozo::get_connection_socket_impl template. Default specialization may look like this (for exposition only):
template <typename T, typename = std::void_t<>>
struct get_connection_socket_impl {
    template <typename Conn>
    constexpr static auto apply(Conn&& c) -> decltype((c.socket_)) {
        return c.socket_;
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — Connection object
Returns
reference or proxy to the socket object
Referenced by ozo::get_socket().
get_connection_timer()
template<typename T > constexpr auto ozo::get_connection_timer (T && conn)
Get the connection timer object.
OZO is all about IO. IO can be for a long time, so almost every user sooner or later needs a timeout for an IO. This library provides such functionality of time-outs. For a time-out implementation the library needs a timer. So this is it. Originally the library expects boost::asio::basic_waitable_timer as a timer interface and uses boost::asio::steady_timer as the default implementation. But this place can be customized.
Customization Point
This is customization point for Connection concept implementation. To customize it please specialize ozo::get_connection_timer_impl template. Default specialization may look like this (for exposition only):
template <typename T, typename = std::void_t<>>
struct get_connection_timer_impl {
    template <typename Conn>
    constexpr static auto apply(Conn&& c) -> decltype((c.timer_)) {
        return c.timer_;
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — Connection object
Returns
timer for the Connection
Referenced by ozo::get_timer().
get_error_context()
template<typename T > const auto& ozo::get_error_context (const T & conn)
Gives additional error context from OZO.
Like libpq OZO provides additional context for different errors which can be while interacting via connection. This function gives access for such context.
See also
ozo::set_error_context(), ozo::reset_error_context()
Parameters
conn — Connection to get context from
Returns
std::string contains a context
References ozo::get_connection_error_context(), and ozo::unwrap_connection().
get_handle()
template<typename T > decltype(auto) ozo::get_handle (T && conn) noexcept
PostgreSQL connection handle.
PostgreSQL native connection handle wrapped with RAII smart pointer. In common cases you do not need this function. It's purpose is to support extention and customization of the library. See get_native_handle for details.
Parameters
conn — Connection objec
Returns
refernce to a wrapped PostgreSQL connection handle
References ozo::get_connection_handle(), and ozo::unwrap_connection().
Referenced by ozo::close_connection(), and ozo::get_native_handle().
get_io_context()
template<typename T > decltype(auto) ozo::get_io_context (T & conn) noexcept
IO context for a connection is bound to.
Parameters
conn — Connection object
Returns
io_context of socket stream object of the connection
References ozo::get_socket().
get_native_handle()
template<typename T > decltype(auto) ozo::get_native_handle (T && conn) noexcept
PostgreSQL native connection handle.
In common cases you do not need this function. It's purpose is to support extention and customization of the library. So if you want do extend or customize some behaviour via original libpq calls this is what you really need. In other cases this is not the function what you are looking for.
Parameters
conn — Connection object
Returns
PQConn* — native handle
References ozo::get_handle().
Referenced by ozo::connection_bad(), and ozo::error_message().
get_oid_map()
template<typename T > decltype(auto) ozo::get_oid_map (T && conn) noexcept
Access to a connection OID map.
This function gives access to a connection OID map, which represents mapping of custom types to its' OIDs in a database connected to.
Parameters
conn — Connection to access OID map of
Returns
OID map of the Connection
References ozo::get_connection_oid_map(), and ozo::unwrap_connection().
get_socket()
template<typename T > decltype(auto) ozo::get_socket (T && conn) noexcept
Socket stream object of the connection.
See underlying ozo::get_connection_socket for details.
Parameters
conn — Connection object
Returns
socket stream object of the connection
References ozo::get_connection_socket(), and ozo::unwrap_connection().
Referenced by ozo::close_connection(), and ozo::get_io_context().
get_statistics()
template<typename T > decltype(auto) ozo::get_statistics (T && conn) noexcept
Access to a Connection statistics.
Note
This feature is not implemented yet
Parameters
conn — Connection to access statistics of
Returns
statistics of the Connection
References ozo::unwrap_connection().
get_timer()
template<typename T > decltype(auto) ozo::get_timer (T && conn) noexcept
Access to a timer for connection operations.
This function is dedicated to a timer access. Since our API provides time-outs for IO operations it needs a timer. After weeks of experiments we decide to keep timer in the Connection. So this function should provide entity with boost::asio::basic_waitable_timer compatible interface (in common cases it is a reference to boost::asio::steady_timer).
Parameters
conn — Connection to access statistics of
Returns
a reference or proxy for a timer
References ozo::get_connection_timer(), and ozo::unwrap_connection().
make_connection_pool()
template<typename Source > auto make_connection_pool (Source && source, const connection_pool_config & config) related
Connection pool construct helper function.
Parameters
source — ConnectionSource object which is being used to create connection to a database.
config — pool configuration.
Returns
connection_pool constructed object
rebind_io_context()
template<typename T , typename IoContext > error_code ozo::rebind_io_context (T & conn, IoContext & io)
Rebinds io_context for the connection.
Parameters
conn — Connection which must be rebound
io — io_context to which conn must be bound
Returns
error_code in case of error has been
References ozo::unwrap_connection().
reset_error_context()
template<typename T > void ozo::reset_error_context (T & conn)
Reset connection OZO-related error context.
This function resets OZO-related error context to default.
See also
ozo::set_error_context(), ozo::get_error_context()
Parameters
conn — Connection to reset context to
References ozo::set_error_context().
set_error_context()
template<typename T , typename Ctx > void ozo::set_error_context (T & conn, Ctx && ctx)
Set connection OZO-related error context.
Like libpq OZO provides additional context for errors. This function sets such context for the specified connection.
See also
ozo::get_error_context(), ozo::reset_error_context()
Parameters
conn — Connection to set context to
ctx — context to set, now only std::string is supported
References ozo::get_connection_error_context(), and ozo::unwrap_connection().
Referenced by ozo::reset_error_context().
unwrap_connection()
template<typename T > decltype(auto) constexpr ozo::unwrap_connection (T && conn) noexcept
Unwrap connection if wrapped with Nullable.
Unwraps wrapped connection recursively. Returns unwrapped connection object.
Customization Point
This is customization point for the Connection enhancement. To customize it it is better to specialize ozo::unwrap_connection_impl template for custom type. E.g. such overload is used for the ozo::impl::pooled_connection of this library. The deafult implementation of the function is perfect forwarding. And may look like this (for exposition only - actual implementation may be different):
template <typename, typename = std::void_t<>>
struct unwrap_connection_impl {
    template <typename Conn>
    static constexpr decltype(auto) apply(Conn&& conn) noexcept {
        return std::forward<Conn>(conn);
    }
};
If you are specialize the template for your own parameterized connection wrapper implementation do not forget to call unwrap_connection for the underlying connection type. E.g.:
template <typename T>
struct unwrap_connection_impl<T, Require<Nullable<T>>>{
    template <typename Conn>
    static constexpr decltype(auto) apply(Conn&& conn) noexcept {
        return unwrap_connection(*conn);
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — wrapped or unwrapped Connection
Returns
unwrapped Connection object reference
Referenced by ozo::get_error_context(), ozo::get_handle(), ozo::get_oid_map(), ozo::get_socket(), ozo::get_statistics(), ozo::get_timer(), ozo::rebind_io_context(), and ozo::set_error_context().